basePath: /api
definitions:
  model.Student:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  response.ErrorDetail:
    properties:
      code:
        type: integer
      details:
        type: string
      message:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/response.ErrorDetail'
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: hongphucle1010@gmail.com
    name: HCMUT Team at Fsoft
  description: This is a sample server Student Management System.
  termsOfService: http://swagger.io/terms/
  title: Swagger Student Management System API
  version: "1.0"
paths:
  /students/:
    get:
      consumes:
      - application/json
      description: Get all students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Student'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get all students
      tags:
      - students
swagger: "2.0"
