basePath: /api
definitions:
  model.Student:
    properties:
      dob:
        type: string
      email:
        type: string
      gpa:
        type: number
      id:
        type: integer
      name:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      details:
        type: string
      message:
        type: string
    type: object
  response.SuccessResponse-any:
    properties:
      data: {}
      message:
        type: string
    type: object
  response.SuccessResponse-array_model_Student:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Student'
        type: array
      message:
        type: string
    type: object
info:
  contact:
    email: hongphucle1010@gmail.com
    name: HCMUT Team tại FPT Software HCM
  description: Tài liệu API của hệ thống quản lý sinh viên
  termsOfService: http://swagger.io/terms/
  title: Swagger UI Hệ thống quản lý sinh viên
  version: "1.0"
paths:
  /ping/:
    get:
      description: Ping to get pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Health check
      tags:
      - ping
  /students/:
    get:
      description: Get all students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse-array_model_Student'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get all students
      tags:
      - students
  /test/:
    get:
      description: Get test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get test
      tags:
      - test
swagger: "2.0"
